### ISSUE TITLE
get the chainId for BlockData

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Consensys/besu-sequencer-plugins#1209]

**Comment by DavePearce** [comment]
Rough notes:

* `ZkTracer` needs a "master chainID" which should be set specifically before tracing begins (e.g. for the replay tests it would be captured and then stored in the conflation and set by the `ReplayExecutionEnvironment`).
* The chainID cannot necessarily be inferred from the available transactions because some transactions don't have a chainID.  Thus, in the worst case scenario, a block could exist which has only transactions without chainIDs.
* Its not immediately clear how to extract the "master chainID" from BESU (but presumably it is possible).

**Comment by letypequividelespoubelles** [comment]
the PR won't work in case all txs of the batch are unprotected. Will need  https://github.com/hyperledger/besu/issues/7630 for a proper fix

**Comment by OlivierBBB** [comment]
> the PR won't work in case all txs of the batch are unprotected

This issue is very common in the `BlockchainReferenceTest`'s

**Comment by letypequividelespoubelles** [comment]
duplicate create #1357
