### ISSUE TITLE
add PUB_HASH and PUB_LOG counter in Besu which replicates geth counting

### ISSUE THREAD

**Issue by FlorianHuc** [Consensys/besu-sequencer-plugins#517]
Line counting should replicate the one happening in Geth.

**Comment by OlivierBBB** [comment]
There are fundamental arithmetization changes between the Geth and Besu:
- Geth logs everything in pub_log, even those logs that would get discarded due to internal transactions reverting, Besu doesn't do that; Besu looks at the transaction receipt produced in the end and inserts those logs only;
- Besu hashes more stuff: deployment code when returning from a CREATE(2) + initialization code  for CREATE2
