### ISSUE TITLE
for deployments again the `ToyWorld` produces out of sync `addressAccountMap` and `accounts` list

### ISSUE THREAD

**Issue by OlivierBBB** [Consensys/besu-sequencer-plugins#967]

**Comment by DavePearce** [comment]
@OlivierBBB So, I noticed this when looking at `ToyWorld` and removed the `accounts` list in #966 (because its not otherwise being used).  What problem was it causing you, or is this just an observation you made?  For reference, you can see the `SimpleWorld` implementation which is part of BESU [here](https://github.com/hyperledger/besu/blob/main/evm/src/main/java/org/hyperledger/besu/evm/fluent/SimpleWorld.java).

**Comment by OlivierBBB** [comment]
@DavePearce I'm not sure why it was introduced, @powerslider didn't remember when we discussed this a while back. The issue it was causing was it being used as a source of stuff to do but being out of sync with the similar `HashMap`. So IIRC it would be empty or only contain the sender or so for deployment transactions. Something like that.

**Comment by letypequividelespoubelles** [comment]
I guess we can close this @OlivierBBB  @DavePearce  ?
